### ISSUE TITLE
`psysh ^0.7` in composer.json made psalm can not install

### ISSUE THREAD

**Issue by haoliang-gao** [yiisoft/yii2-shell#13]
### What steps will reproduce the problem?

* composer install yiisoft/yii2-shell
* composer install vimeo/psalm

the dependency chain is:

* psalm -> nikic/php-parser
* yii2-sell -> psysh -> php-parser

### What's expected?

If yii2-shell is compatiable with psysh ^0.8, please update the composer.json.

### What do you get instead?

dependency unsatisfied

```
  Problem 1
    - Installation request for vimeo/psalm ^0.3.24 -> satisfiable by vimeo/psalm[0.3.24].
    - Conclusion: remove nikic/php-parser v2.1.0
    - Conclusion: don't install nikic/php-parser v2.1.0
    - vimeo/psalm 0.3.24 requires nikic/php-parser ^3.0.4 -> satisfiable by nikic/php-parser[3.x-dev, v3.0.4].
    - Can only install one of: nikic/php-parser[3.x-dev, v2.1.0].
    - Can only install one of: nikic/php-parser[v3.0.4, v2.1.0].
    - Installation request for nikic/php-parser (locked at v2.1.0) -> satisfiable by nikic/php-parser[v2.1.0].
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii2-shell vesion       | dev-master 9843b89
| PHP version      | 7.1.2
| Operating system | archlinux

**Comment by samdark** [comment]
Fixed by https://github.com/yiisoft/yii2-shell/commit/4e06caae569b158190758f0ad52d48a6c74b28e4
