### ISSUE TITLE
Feature Request: add Events to yii\db\Connection

### ISSUE THREAD

**Issue by thyseus** [yiisoft/yii2-shell#14]
Hey, 

is it possible to do something like this from laravel 5.3+?:

https://laravel.com/docs/5.3/database#listening-for-query-events

```php

        DB::listen(function ($query) {
            var_dump( $query->sql);
            var_dump( $query->bindings);
            var_dump( $query->time);
        });

```

which would (pseudo code) look something like this in yii2:

```php
$db = Yii::$app->db

$db->on(yii\db\Connection::EVENT_SQL_EXECUTED, function($query) { var_dump ($query); } );
```

Is something like this already possible? I am asking here because in a REPL this feature will most probably useful.

Thanks !

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/issues/14593

**Comment by samdark** [comment]
Won't fix.
