### ISSUE TITLE
Add symfony/var-dumper as a requirement?

### ISSUE THREAD

**Issue by javiereguiluz** [yiisoft/yii2-shell#15]
### What steps will reproduce the problem?

In this class: https://github.com/yiisoft/yii2-shell/blob/master/YiiCaster.php you import a Symfony class: `use Symfony\Component\VarDumper\Caster\Caster;` but you don't require `symfony/var-dumper` in the `composer.json` of this project: https://github.com/yiisoft/yii2-shell/blob/master/composer.json

This works by chance and pure luck. Some package is installing the package you need (`symfony/var-dumper`) so this works without you actually requiring that package.

### What's expected?

`symfony/var-dumper` should be added to the `require` section of the `composer.json` file.

### What do you get instead?

-

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | Any
| PHP version      | Any
| Operating system | Any

**Comment by schmunk42** [comment]
Makes sense.

We also should create a new release, since there was another requirement update for `psy/psysh`.
The latest stable release requires symfony/console 2.x

**Comment by samdark** [comment]
@javiereguiluz totally makes sense. Would you like to handle it in a pull request?

**Comment by pana1990** [comment]
@javiereguiluz @samdark @schmunk42 psy/psysh has already "symfony/var-dumper" dependency in her composer.json : https://github.com/bobthecow/psysh/blob/master/composer.json#L18

is it necessary to include it in our composer?

**Comment by schmunk42** [comment]
Yes, since it's used here. If they would remove the dep i.e. our code would break.

**Comment by javiereguiluz** [comment]
@pana1990 a general rule is that if your own code uses some third-party code directly, you should add it to `require` or `require-dev`. In this case, Yii2 is explicitly importing a Symfony class in this line: https://github.com/yiisoft/yii2-shell/blob/master/YiiCaster.php

**Comment by pana1990** [comment]
Of course, thanks for your reply :)

**Comment by bertoost** [comment]
Why is a production package using VarDumper? This is a dev package and now it becomes a production package which also brings some other disadvantages because of this. Since I now can not use latest version of it in dev environments.
Therefore I cannot find the real usage of this Symfony component. Is it really necessary?
