### ISSUE TITLE
Release yii2-shell:2.0.2

### ISSUE THREAD

**Issue by ddinchev** [yiisoft/yii2-shell#23]
I need to upgrade to `psysh:0.9.x` due to dependency on `nikic/php-parser:4.0`. There has been an issue #19 that was resolved 8 months ago and scheduled for `yii2-shell:2.0.2` which was never released. Is there a reason why we can't have this bugfix out?

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-shell/releases/tag/2.0.2
