### ISSUE TITLE
Does not fully support PHP 7.4

### ISSUE THREAD

**Issue by hunwalk** [yiisoft/yii2-shell#25]
### Doc and show commands do not fully support php 7.4

<img width="1064" alt="kép" src="https://user-images.githubusercontent.com/32835435/73545788-53a0e000-443c-11ea-92c2-bf7602535edd.png">

### Additional info
| Yii vesion: 2.0.30 |
| PHP version: 7.4 |
| Operating system: macOs Mojave(10.14.6) |

**Comment by samdark** [comment]
Any idea where exception is coming from?

**Comment by xepozz** [comment]
I think it related to https://github.com/bobthecow/psysh because it provide `doc` command, not yii2 or any `yii2-` libraries.

**Comment by xepozz** [comment]
I found at least one problem at https://github.com/bobthecow/psysh/blob/master/src/Formatter/SignatureFormatter.php#L290

**Comment by xepozz** [comment]
https://github.com/bobthecow/psysh/pull/605

**Comment by samdark** [comment]
As @xepozz pointed out, it is a bug of psysh. Until a new version is released, it can't be resolved.
