### ISSUE TITLE
Reconsider VarDumper component as package requirement

### ISSUE THREAD

**Issue by bertoost** [yiisoft/yii2-shell#26]
Since VarDumper is a dev package and it now becomes a normal requirement. Therefore it's not really used as far I have scanned the code. This also break projects which already using a newer version of the VarDumper component as dev package.

Also see;
https://github.com/yiisoft/yii2-shell/issues/15

**Comment by samdark** [comment]
The usage is here: https://github.com/yiisoft/yii2-shell/blob/master/YiiCaster.php#L34

**Comment by bertoost** [comment]
But I can't imagine this is the only way. Using VarDumper for this purpose is not good. There should be an other way

**Comment by rob006** [comment]
> This also break projects which already using a newer version of the VarDumper component as dev package.

This probably could be fixed by adding `|~5.0` constraint in:

https://github.com/yiisoft/yii2-shell/blob/bef95cffe0833230f376091bf1da0cd971d595dc/composer.json#L30

I doubt there is anything more to do to provide Symfony 5 support.

**Comment by bertoost** [comment]
#disappointed :-(

**Comment by samdark** [comment]
@bertoost why? var-dumper [is a sub-dependency of psysh anyway](https://github.com/bobthecow/psysh/blob/master/composer.json#L20). What we're doing is specifying explicitly that we're using code from it as well.

**Comment by bertoost** [comment]
VarDumper is a dev package, also is Psysh, and should not be used as normal dependency. Now every project using this package is contaminated with this dev package.
That's why I am disappointed you just close this instead of reconsidering a refactor on this package.

Btw. the first line on the Psysh website/repo is "A runtime developer console, interactive debugger and REPL for PHP."
So, it's for development, not for production environments. And now it becomes a production package.

**Comment by rob006** [comment]
@bertoost This package is a wrapper for Psysh. If you think that Psysh or VarDumper should not be installed on production, you shouldn't have `yii2-shell` on production either.

**Comment by bertoost** [comment]
But this is the shell package for Yii2, which should be used if you want the console functionalities in Yii2. So, how is it possible that a production package uses dev packages as dependency?

**Comment by rob006** [comment]
> But this is the interactive shell package for Yii2, which should be used if you want the console functionalities in Yii2.

What functionalities? You can run console commands without this package.

**Comment by samdark** [comment]
yii2-shell is for interactive trying things out / debugging / fiddling with code. As @rob006 mentioned, it's not required to run console commands.

**Comment by bertoost** [comment]
Ah I have checked, and it is indeed explicitly required in the system I use (Craft CMS). I have contacted the maintainers to ask them if the package should be required anyway, since I can't find any usage on the namespace. 
Sorry for being such a pain, not meant to be :-)

**Comment by samdark** [comment]
@bertoost that's alright. Glad that it's clarified.
