### ISSUE TITLE
Upgrade to PsySH ~0.10.3

### ISSUE THREAD

**Issue by tobiase** [yiisoft/yii2-shell#27]
Currently, yii2-shell depends on "psy/psysh": "~0.9.3"
This version of psysh requires abandoned packages and warnings are shown on installation.
The newer version seems to work fine. I tested it with opening the shell and accessing `Yii::$app`.

**Comment by samdark** [comment]
Does it work with the same minimal PHP version well?

**Comment by rob006** [comment]
0.10.x requires at least PHP `^5.5.9`.

**Comment by samdark** [comment]
How about using `"psy/psysh": "~0.9.3|~0.10.3"` then?

**Comment by tobiase** [comment]
I updated the pull request with the suggested `"psy/psysh": "~0.9.3|~0.10.3"`
