### ISSUE TITLE
Disable update check

### ISSUE THREAD

**Issue by flaviovs** [yiisoft/yii2-shell#32]
### What steps will reproduce the problem?

Run `yii shell`

### What's expected?

The command executing without making any network connections other than the one requested by shell commands.

### What do you get instead?

The command "phones home" to check for updates.

![image](https://github.com/yiisoft/yii2-shell/assets/1832699/c980698f-01e5-4174-bc73-343ec2eaf4df)

### Additional info

Although staying up-to-date is desirable, for privacy, security, and/or compliance reasons some environments must allow only authorized and audited libraries to call external hosts.

A psysh `updateCheck` option does exist to disable the check (see https://github.com/bobthecow/psysh/wiki/Config-options), but it is enabled by default and I could not find any mechanism in yii2-shell to turn that off.

My suggestion is to provide a corresponding `updateCheck` options to the shell component that would be passed directly to psysh, so Yii2 applications could control the check.

IMHO this options should be "never" by default, but I'd be fine if the default behaviour is kept if an option to control it is available.

| Q                | A
| ---------------- | ---
| Yii version       | 2.0.47
| PHP version      | 7.4
| Operating system | Linux Debian Bullseye

**Comment by samdark** [comment]
Good to have the option and it being disabled by default. Do you have some time for a pull request?

**Comment by flaviovs** [comment]
Hi @samdark - I'll see if I can prepare something by the end of this week. It looks like a straightforward change. I'll let you know.

**Comment by flaviovs** [comment]
Here's the PR, simpler than I expected.

Let me know if you need anything regarding this.

Thank you

**Comment by samdark** [comment]
All good. It's in `master` now.
