### ISSUE TITLE
Incompatibility with yii2-apidoc?

### ISSUE THREAD

**Issue by devleaks** [yiisoft/yii2-shell#5]
Hello,
I tried to install yii2-shell but bumped into the following Composer conflict:
- yii2-shell requires psy/psysh which requires nikic/php-parser: "^1.2.1|~2.0".
- I have yii2-apidoc which requires nikic/php-parser: "0.9.*. Bump.

I don't know nikic/php-parser details, but is there a workaround for this?
Is it concievable to update yii2-apidoc's requirement to something compatible with yii2-shell's?
Thanks.
Pierre

**Comment by samdark** [comment]
@cebe ?

**Comment by cebe** [comment]
Thanks for reporting this. Will look into it.

**Comment by samdark** [comment]
@cebe any progress on it? The extension is otherwise solid. I've tested it and fixed very minor issues.

**Comment by cebe** [comment]
will look into it this week.

**Comment by samdark** [comment]
@cebe have you checked this one?

**Comment by cebe** [comment]
released apidoc 2.1 which is now compatible.
